export { default as About } from './About';
export { default as Header } from './Header';
export { default as Navbar } from './Navbar';
export { default as Education } from './Education';
export { default as Experience } from './Experience';
export { default as Skills } from './Skills';
export { default as Services } from './Services';
export { default as Portfolio } from './Portfolio';
export { default as Footer } from './Footer';